# Extending image
FROM node:carbon

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get -y install autoconf automake libtool nasm make pkg-config git apt-utils

# Install yarn
RUN rm -f /usr/local/bin/yarn && \
  curl -o- -L https://yarnpkg.com/install.sh | bash && \
  chmod +x ~/.yarn/bin/yarn && \
  ln -s ~/.yarn/bin/yarn /usr/local/bin/yarn

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Versions
RUN npm -v
RUN node -v
RUN yarn -v

# Install app dependencies
COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app

RUN yarn install

# Bundle app source
COPY . /usr/src/app

# Environment variables
ENV NODE_ENV test
ENV CI true

# Main command
CMD [ "yarn", "test" ]
